[package]
name = "polyfuse-kernel"
version = "0.1.0"
description = "FUSE application binary interface for `polyfuse`."
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
zerocopy = "0.3.0"
