[package]
name = "polyfuse-kernel"
version = "0.2.0-dev"
publish = false
description = "FUSE application binary interface for `polyfuse`."
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.78.0"

[dependencies]
zerocopy = { version = "0.8.26", features = [ "derive" ] }
