name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: full
  CARGO_TERM_COLOR: always

permissions:
  contents: read # only fetching code is available

jobs:
  Test:
    runs-on: ubuntu-24.04
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v5

    - run: rustup set profile minimal
    - uses: taiki-e/install-action@nextest
    - uses: taiki-e/install-action@cargo-llvm-cov
    - uses: Swatinem/rust-cache@v2

    - name: Run tests (MSRV)
      run: |
        set -xe
        cargo --version
        cargo fmt -- --check
        cargo clippy
        cargo nextest run
        cargo test -p polyfuse-kernel-systest

    - name: Run tests (stable)
      run: |
        set -xe
        cargo +stable nextest run
        cargo +stable test -p polyfuse-kernel-systest
  
    - name: Run coverage test
      id: coverage
      run: cargo +stable llvm-cov --codecov --output-path codecov.json
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: codecov.json
